# parameters
num_classes: 8  # number of classes
depth_multiple: 0.67  # model depth multiple
width_multiple: 0.75  # layer channel multiple
detect_strides: [32, 16, 8]
dim_ref:
  [[1.52607842, 1.62858147, 3.88396124], # h, w, l
  [2.20649159, 1.90197734, 5.07812564],
  [3.25207685,  2.58505032, 10.10703568],
  [1.76067766, 0.6602296 , 0.84220464],
  [1.27538462, 0.59506787, 0.80180995],
  [1.73712792, 0.59677122, 1.76338868],
  [3.52905882,  2.54368627, 16.09707843],
  [1.9074177, 1.51386831, 3.57683128]]
# anchors
anchors:
  - [106,68,  175,105,  262,140]  # P5/32
  - [44,32,  75,37,  46,95]  # P4/16
  - [19,16,  15,40,  32,22]  # P3/8

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, BottleneckCSP, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]], # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
  ]

# YOLOv5 head
head:
  [[-1, 3, BottleneckCSP, [1024, False]],  # 9

   [-1, 1, Conv, [512, 1, 1]], # 10
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, BottleneckCSP, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]], # 14
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, BottleneckCSP, [256, False]], # 17 -----(P3/8-small ---> detect)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, BottleneckCSP, [512, False]], # 20 -----(P4/16-medium ---> detect)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, BottleneckCSP, [1024, False]], # 23 -----(P5/32-large ---> detect)

   [[-1, 20, 17], 1, Detect, []],  # Detect(P5, P4, P3)
  ]
